# Generated by Django 3.1 on 2020-08-19 01:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_auto_20200818_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="people_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=30, null=True),
                    size=None,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
