#!/bin/sh

BRANCH=`git branch --show-current`

echo ""
echo "This one is a bit tough, so do it yourself for now."
echo "If the pre-commits reject the code they may change it and you need to add the files again."
echo ""
echo "Run this until it works:"
echo ""
echo "git add -A"
echo "git commit -m \"$BRANCH\""
echo ""
echo "Then run this:"
echo ""
echo "git push origin $BRANCH"
echo ""
echo ""
