branch-defaults:
  master:
    environment: cobalt-test
    group_suffix: null
environment-defaults:
  cobalt-dev:
    branch: null
    repository: null
global:
  application_name: cobalt
  branch: null
  default_ec2_keyname: mgcobalt
  default_platform: Python 3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
